import { SiteContent } from "./content-types";

export const DEFAULT_CONTENT: SiteContent = {
  fr: {
    nav: { about: "À propos", services: "Services", experience: "Parcours", contact: "Contact" },
    hero: {
      eyebrow: "Freelance · Product Leadership",
      subtitle: "Product Leader Building AI",
      lede: "J'aide les entreprises SaaS, B2B et B2C à structurer leur produit, leur data et leurs équipes — de la stratégie à la mise en production.",
      ctaPrimary: "Discuter de mon projet",
      ctaSecondary: "Voir le parcours",
      availability: "Disponible pour missions courtes ou longues, temps plein ou partiel · Remote ou Paris",
    },
    metrics: [
      { value: "-15 pts", label: "de churn (discovery IA)" },
      { value: "125K€/an", label: "économisés (digitalisation)" },
      { value: "x2,8", label: "conversion (1,25% → 3,5%)" },
      { value: "7 mois", label: "de la vision au MVP" },
    ],
    about: {
      title: "Apprendre à me connaître",
      p1: "Ingénieure de formation (Télécom SudParis), j'ai construit ma carrière autour d'un fil rouge : transformer des données complexes et des organisations en produits qui créent de la valeur — chez Renault, MSD, Openclassrooms ou Europcar.",
      p2: "Française et marocaine, basée à Paris, je travaille couramment en anglais et j'apprends l'IA en continu (diplôme Openclassrooms). En tant que Senior Product Manager et Product Owner, j'allie stratégie produit, product roadmap, discovery, méthodologie agile (Scrum), product design et user experience design, avec un vrai sens du management d'équipe. Ce qui me motive : le terrain, les équipes, et les résultats mesurables.",
      values: ["Rigueur", "Impact mesurable", "Leadership bienveillant", "Curiosité IA", "Product Ops"],
      sectorsTitle: "Secteurs d'activité",
      sectors: ["Automobile & mobilité", "Santé & pharma", "EdTech", "SaaS & cybersécurité", "Médias"],
      interestsTitle: "Centres d'intérêt",
      interests: ["Sport", "Voyages", "Musique"],
    },
    services: {
      hint: "Cliquez sur un service pour voir le détail.",
      doLabel: "Ce que je fais concrètement",
      getLabel: "Ce que vous obtenez",
      backLabel: "Retour aux services",
      list: [
        {
          title: "Pilotage de produits Data & IA",
          audienceLabel: "Pour qui",
          audience:
            "Entreprises qui ont des projets data ou IA critiques, mais pas de Product Manager expérimenté (AI Product Manager ou Data Product Manager) pour les porter de bout en bout.",
          problem: "Vos initiatives data/IA restent bloquées entre les équipes techniques, la direction et les métiers — personne n'a la vision complète ni l'autorité pour trancher et faire avancer.",
          skills: ["Gouvernance de la donnée", "Qualité des données", "Conformité", "Pilotage par la donnée", "Gestion des parties prenantes"],
          whatIDo: [
            "Cadrage des besoins et définition de la roadmap produit",
            "Gouvernance data opérationnelle (propriétaires, règles de qualité, priorisation)",
            "Interface entre business, Conformité, Opérations, Tech et direction",
            "Pilotage via tableaux de bord et indicateurs de suivi",
            "Animation des comités et arbitrages rapides",
          ],
          whatYouGet: [
            "Une roadmap claire et exécutée, pas juste documentée",
            "Une donnée fiable et gouvernée, avec des règles de qualité en place",
            "Une direction qui pilote sur des indicateurs à jour, pas sur du reporting manuel",
            "Un point de contact unique qui absorbe la complexité multi-équipes",
          ],
        },
        {
          title: "Pilotage de produits digitaux B2C / B2B",
          audienceLabel: "Pour qui",
          audience: "Entreprises qui lancent ou font évoluer un produit — B2C ou B2B, site web, application, SaaS ou software — mais manquent d'un Product Manager capable de porter la vision de bout en bout.",
          problem: "Votre produit avance sans réelle vision, ou les priorités changent en permanence faute d'une roadmap claire ancrée dans les besoins utilisateurs et les objectifs business.",
          skills: ["Stratégie produit", "Product Roadmap", "Discovery", "Méthodologie Agile", "Product Owner"],
          whatIDo: [
            "Définition de la stratégie et de la roadmap produit, du MVP aux itérations orientées marché",
            "Discovery utilisateur et user experience design (entretiens, tests, analyse data) pour ancrer les décisions dans le réel",
            "Animation du backlog et pilotage du cycle discovery → delivery en méthodologie Agile (Scrum)",
            "Management ou coordination d'une équipe produit",
            "Alignement transverse",
          ],
          whatYouGet: [
            "Une roadmap claire, priorisée par la valeur business et utilisateur",
            "Un produit qui avance avec une vision cohérente plutôt qu'au fil des urgences",
            "Une équipe alignée et un cycle de delivery fluide",
            "Des décisions produit ancrées dans la donnée et les retours utilisateurs, pas dans les suppositions",
          ],
        },
        {
          title: "Pilotage de projets digitaux et de migration",
          audienceLabel: "Pour qui",
          audience: "Entreprises menant un projet de transformation digitale complexe — lancement de produit, migration de système, mise en conformité réglementaire — souvent à l'international.",
          problem: "Ces projets touchent plusieurs pays, plusieurs équipes, et des contraintes réglementaires strictes (ex. facturation électronique). Sans pilotage rigoureux, les délais et la qualité en pâtissent.",
          skills: ["Gestion de projet", "Migration de données", "SAP", "Facturation électronique", "Déploiement international"],
          whatIDo: [
            "Cadrage des besoins, découpage en lots, définition des jalons",
            "Pilotage de migrations de données (migration SAP, refonte de systèmes)",
            "Mise en conformité réglementaire",
            "Coordination de déploiements à l'international, gestion des dépendances entre équipes",
            "Suivi de production et gestion des incidents post-lancement",
          ],
          whatYouGet: [
            "Un projet livré dans les délais réglementaires, sans rupture pour le business",
            "Une migration sécurisée, avec tests et fiabilisation des données",
            "Une coordination fluide entre les pays, les métiers et la tech",
            "Une visibilité claire sur l'avancement, les risques et les décisions à prendre",
          ],
        },
        {
          title: "Construction d'agents IA et d'automatisations",
          audienceLabel: "Pour qui",
          audience: "PME et entreprises qui veulent automatiser des tâches répétitives ou intégrer l'IA à leurs process, sans recruter une équipe data science.",
          problem: "Vous savez que l'IA peut vous faire gagner du temps, mais vous ne savez pas par où commencer, ni comment construire quelque chose de fiable et adapté à votre activité.",
          skills: ["Agents IA", "Automatisation", "n8n", "Make", "Dust"],
          whatIDo: [
            "Identification des cas d'usage à plus fort impact (support, ventes, reporting, back-office)",
            "Construction d'agents et de workflows automatisés (n8n, Make, Dust)",
            "Intégration avec vos outils existants (CRM, ERP, bases de données)",
            "Tests et itérations pour fiabiliser les résultats avant mise en production",
          ],
          whatYouGet: [
            "Des tâches manuelles automatisées, du temps libéré pour vos équipes",
            "Des outils IA construits sur mesure pour votre activité, pas des solutions génériques",
            "Une mise en place progressive et testée, sans pari risqué sur la technologie",
          ],
        },
        {
          title: "Chatbots commerciaux sur mesure",
          audienceLabel: "Pour qui",
          audience: "Entreprises qui veulent digitaliser une partie de leur relation client ou de leurs ventes (renseignement produit, prise de commande, génération de leads).",
          problem: "Vos clients veulent des réponses immédiates et personnalisées, mais votre équipe commerciale ne peut pas être disponible partout, tout le temps.",
          skills: ["IA conversationnelle", "API Claude", "Génération de leads", "Architecture chatbot"],
          whatIDo: [
            "Conception de l'expérience conversationnelle et des parcours client",
            "Développement de l'architecture complète : backend, intégration IA, panel d'administration",
            "Connexion à vos données réelles (stock, prix, catalogue) pour des réponses fiables, pas génériques",
            "Mise en place d'un suivi des conversations et des leads générés",
          ],
          whatYouGet: [
            "Un assistant conversationnel disponible en continu, connecté à vos vraies données",
            "Une génération de leads ou de ventes automatisée",
            "Une visibilité complète sur les échanges via un panel d'administration",
            "Un outil qui s'appuie sur des données à jour, pas sur des réponses approximatives",
          ],
        },
        {
          title: "Audit et stratégie IA",
          audienceLabel: "Pour qui",
          audience: "Entreprises traditionnelles qui veulent adopter l'IA mais ne savent pas par où commencer ni ce qui est réellement pertinent pour elles.",
          problem: "L'IA est partout dans les discours, mais peu d'entreprises ont une vision claire de ce qu'elles peuvent réellement en tirer, avec quel investissement et quel retour.",
          skills: ["Stratégie IA", "Faisabilité technique", "Roadmap IA", "Make or Buy"],
          whatIDo: [
            "Audit de vos process et identification des cas d'usage IA à fort potentiel",
            "Évaluation réaliste : faisabilité technique, coût, impact attendu",
            "Recommandations priorisées, avec une feuille de route concrète",
            "Accompagnement dans le choix entre solutions existantes, développement sur mesure, ou achat externe",
          ],
          whatYouGet: [
            "Une feuille de route IA claire et priorisée, adaptée à votre réalité",
            "Des décisions basées sur des cas d'usage concrets, pas sur des effets de mode",
            "Une base solide pour investir sereinement dans l'IA",
          ],
        },
      ],
    },
    experience: [
      {
        company: "Europcar Mobility Group",
        role: "Principal Data & AI Product Expert",
        period: "2024 – 2025",
        highlights: ["Migration SAP multi-pays et multi-marques", "Facturation électronique BE et FR"],
      },
      {
        company: "Openclassrooms",
        role: "Staff Solution Manager",
        period: "2021 – 2023",
        highlights: [
          "Structuration Product Ops : rituels, process et gouvernance transverse",
          "Mise en place de la visio-conférence",
          "Digitalisation du parcours diplômes",
          "Marketplace apprentis-recruteurs",
          "Revamp de l'app iOS",
          "POC IA pour améliorer l'apprentissage",
        ],
      },
      {
        company: "Olfeo",
        role: "Lead Product",
        period: "2020 – 2021",
        highlights: ["Produit SaaS de cybersécurité en Cloud souverain, lancé de zéro au MVP en 7 mois"],
      },
      {
        company: "Renault",
        role: "Configurator Product Manager",
        period: "2017 – 2020",
        highlights: ["Configurateurs véhicules EV et LCV, déployés dans plus de 10 pays"],
      },
      {
        company: "MSD / Aptus Health, Paris",
        role: "Product Owner",
        period: "09/2014 – 12/2016",
        summary: "Pilotage du CMS éditorial d'Univadis, plateforme de distribution de contenus médicaux multi-marchés.",
        highlights: [
          "Co-construction et ownership de la roadmap produit, priorisation du backlog en approche data-informed",
          "Animation des rituels agile et des ateliers de conception avec les équipes tech, UX, Marketing et Data",
          "Delivery cross-fonctionnelle et communication aux sponsors sur l'avancement et les plans de correction",
          "Pilotage de l'adoption multi-marchés et du déploiement de la plateforme en conformité avec les standards qualité",
        ],
      },
    ],
    contact: {
      title: "Travaillons ensemble",
      subtitle: "Une mission, un projet ou juste une question ? Écrivez-moi.",
      formName: "Nom",
      formEmail: "Email",
      formProject: "Type de mission",
      formMessage: "Votre message",
      formSubmit: "Envoyer",
      direct: "Ou directement :",
      thanks: "Merci ! Je reviens vers vous sous 24h.",
    },
    footer: "© 2026 Farah Mokhtari — Paris, France",
  },
  en: {
    nav: { about: "About", services: "Services", experience: "Experience", contact: "Contact" },
    hero: {
      eyebrow: "Freelance · Product Leadership",
      subtitle: "Product Leader Building AI",
      lede: "I help SaaS, B2B and B2C companies structure their product, data and teams — from strategy to production.",
      ctaPrimary: "Discuss your project",
      ctaSecondary: "See my track record",
      availability: "Available for short or long missions, full-time or part-time · Remote or Paris",
    },
    metrics: [
      { value: "-15 pts", label: "churn (AI discovery)" },
      { value: "€125K/yr", label: "saved (digitalization)" },
      { value: "x2.8", label: "conversion (1.25% → 3.5%)" },
      { value: "7 months", label: "from vision to MVP" },
    ],
    about: {
      title: "Get to know me",
      p1: "Trained as an engineer (Télécom SudParis), I've built my career around one thread: turning complex data and organizations into products that create value — at Renault, MSD, Openclassrooms and Europcar.",
      p2: "French-Moroccan, based in Paris, fluent in English, and continuously learning AI (Openclassrooms diploma). As a Senior Product Manager and Product Owner, I combine product strategy, product roadmap, discovery, agile methodology (Scrum), product design and user experience design, with hands-on team management. What drives me: being hands-on, working with teams, and measurable results.",
      values: ["Rigor", "Measurable impact", "Caring leadership", "AI curiosity", "Product Ops"],
      sectorsTitle: "Industries",
      sectors: ["Automotive & mobility", "Health & pharma", "EdTech", "SaaS & cybersecurity", "Media"],
      interestsTitle: "Interests",
      interests: ["Sport", "Travel", "Music"],
    },
    services: {
      hint: "Click a service to see the detail.",
      doLabel: "What I actually do",
      getLabel: "What you get",
      backLabel: "Back to services",
      list: [
        {
          title: "Data & AI product leadership",
          audienceLabel: "Who it's for",
          audience:
            "Companies with critical data or AI initiatives, but no experienced Product Manager (AI Product Manager or Data Product Manager) to drive them end-to-end.",
          problem: "Your data/AI initiatives stay stuck between tech teams, leadership and the business — no one holds the full picture or the authority to decide and move forward.",
          skills: ["Data Governance", "Data Quality", "Compliance", "Data-Driven Decision Making", "Stakeholder Management"],
          whatIDo: [
            "Scoping needs and defining the product roadmap",
            "Operational data governance (owners, quality rules, prioritization)",
            "Interface between business, Compliance, Operations, Tech and leadership",
            "Steering via dashboards and tracking metrics",
            "Running committees and fast trade-offs",
          ],
          whatYouGet: [
            "A clear roadmap that gets executed, not just documented",
            "Reliable, governed data with quality rules in place",
            "Leadership steering on live metrics, not manual reporting",
            "One point of contact absorbing the cross-team complexity",
          ],
        },
        {
          title: "B2C / B2B digital product leadership",
          audienceLabel: "Who it's for",
          audience: "Companies launching or evolving a product — B2C or B2B, website, app, SaaS or software — but lacking a Product Manager able to own the vision end-to-end.",
          problem: "Your product moves forward without real vision, or priorities keep shifting for lack of a roadmap anchored in user needs and business goals.",
          skills: ["Product Strategy", "Product Roadmap", "Discovery", "Agile Methodology", "Product Owner"],
          whatIDo: [
            "Product strategy and roadmap, from MVP to market-driven iterations",
            "User discovery and user experience design (interviews, testing, data analysis) to ground decisions in reality",
            "Backlog management and steering the discovery → delivery cycle using Agile methodology (Scrum)",
            "Managing or coordinating a product team",
            "Cross-team alignment",
          ],
          whatYouGet: [
            "A clear roadmap, prioritized by business and user value",
            "A product moving forward with a coherent vision instead of urgency-driven",
            "An aligned team and a smooth delivery cycle",
            "Product decisions grounded in data and user feedback, not assumptions",
          ],
        },
        {
          title: "Digital & migration project leadership",
          audienceLabel: "Who it's for",
          audience: "Companies running a complex digital transformation project — product launch, system migration, regulatory compliance — often international.",
          problem: "These projects span several countries, teams, and strict regulatory constraints (e.g. e-invoicing). Without rigorous leadership, timelines and quality suffer.",
          skills: ["Project Management", "Data Migration", "SAP", "E-invoicing", "International Rollout"],
          whatIDo: [
            "Scoping needs, breaking down into workstreams, defining milestones",
            "Leading data migrations (SAP migration, system overhauls)",
            "Regulatory compliance",
            "Coordinating international rollouts, managing cross-team dependencies",
            "Production monitoring and post-launch incident management",
          ],
          whatYouGet: [
            "A project delivered within regulatory deadlines, with no business disruption",
            "A secure migration, with testing and data reliability checks",
            "Smooth coordination across countries, business and tech",
            "Clear visibility on progress, risks and decisions to be made",
          ],
        },
        {
          title: "AI agents & automation",
          audienceLabel: "Who it's for",
          audience: "SMBs and companies wanting to automate repetitive tasks or bring AI into their process, without hiring a data science team.",
          problem: "You know AI could save you time, but you don't know where to start or how to build something reliable and fit for your business.",
          skills: ["AI Agents", "Automation", "n8n", "Make", "Dust"],
          whatIDo: [
            "Identifying the highest-impact use cases (support, sales, reporting, back-office)",
            "Building agents and automated workflows (n8n, Make, Dust)",
            "Integration with your existing tools (CRM, ERP, databases)",
            "Testing and iterating to make results reliable before going live",
          ],
          whatYouGet: [
            "Manual tasks automated, time freed up for your teams",
            "AI tools built for your business, not generic solutions",
            "A progressive, tested rollout, with no risky bet on the technology",
          ],
        },
        {
          title: "Custom sales chatbots",
          audienceLabel: "Who it's for",
          audience: "Companies wanting to digitalize part of their customer relationship or sales (product info, order taking, lead generation).",
          problem: "Your customers want instant, personalized answers, but your sales team can't be everywhere, all the time.",
          skills: ["Conversational AI", "Claude API", "Lead Generation", "Chatbot Architecture"],
          whatIDo: [
            "Designing the conversational experience and customer journeys",
            "Building the full architecture: backend, AI integration, admin panel",
            "Connecting to your real data (stock, pricing, catalog) for reliable, non-generic answers",
            "Setting up tracking for conversations and generated leads",
          ],
          whatYouGet: [
            "A conversational assistant available around the clock, connected to your real data",
            "Automated lead or sales generation",
            "Full visibility into exchanges via an admin panel",
            "A tool built on up-to-date data, not approximate answers",
          ],
        },
        {
          title: "AI audit & strategy",
          audienceLabel: "Who it's for",
          audience: "Traditional companies wanting to adopt AI but unsure where to start or what's actually relevant for them.",
          problem: "AI is everywhere in the conversation, but few companies have a clear view of what they can really get from it, at what cost and return.",
          skills: ["AI Strategy", "Technical Feasibility", "AI Roadmap", "Make or Buy"],
          whatIDo: [
            "Auditing your processes and identifying high-potential AI use cases",
            "Realistic assessment: technical feasibility, cost, expected impact",
            "Prioritized recommendations, with a concrete roadmap",
            "Guidance on choosing between existing solutions, custom development, or buying",
          ],
          whatYouGet: [
            "A clear, prioritized AI roadmap suited to your reality",
            "Decisions based on concrete use cases, not trends",
            "A solid foundation to invest confidently in AI",
          ],
        },
      ],
    },
    experience: [
      {
        company: "Europcar Mobility Group",
        role: "Principal Data & AI Product Expert",
        period: "2024 – 2025",
        highlights: ["Multi-country, multi-brand SAP migration", "E-invoicing rollout in Belgium and France"],
      },
      {
        company: "Openclassrooms",
        role: "Staff Solution Manager",
        period: "2021 – 2023",
        highlights: [
          "Structured Product Ops: rituals, process and cross-team governance",
          "Rolled out video-conferencing",
          "Digitalized the diploma journey",
          "Apprentices–recruiters marketplace",
          "iOS app revamp",
          "AI proof-of-concept to improve learning outcomes",
        ],
      },
      {
        company: "Olfeo",
        role: "Lead Product",
        period: "2020 – 2021",
        highlights: ["Sovereign-cloud cybersecurity SaaS product, launched from zero to MVP in 7 months"],
      },
      {
        company: "Renault",
        role: "Configurator Product Manager",
        period: "2017 – 2020",
        highlights: ["EV and LCV vehicle configurators, rolled out in 10+ countries"],
      },
      {
        company: "MSD / Aptus Health, Paris",
        role: "Product Owner",
        period: "09/2014 – 12/2016",
        summary: "Led the editorial CMS for Univadis, a multi-market medical content distribution platform.",
        highlights: [
          "Co-built and owned the product roadmap, prioritizing the backlog with a data-informed approach",
          "Ran agile rituals and design workshops with Tech, UX, Marketing, and Data teams",
          "Cross-functional delivery and stakeholder communication on progress and corrective plans",
          "Led multi-market adoption and platform rollout in line with quality standards",
        ],
      },
    ],
    contact: {
      title: "Let's work together",
      subtitle: "A mission, a project, or just a question? Write to me.",
      formName: "Name",
      formEmail: "Email",
      formProject: "Project type",
      formMessage: "Your message",
      formSubmit: "Send",
      direct: "Or directly:",
      thanks: "Thanks! I'll get back to you within 24h.",
    },
    footer: "© 2026 Farah Mokhtari — Paris, France",
  },
};
